---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading required libraries
````{r result=F}
library(dplyr)
library(ggplot2)
library(lubridate)
library(data.table)
library(reshape2)
library(zoo)
````


## Loading and preprocessing the data
```{r}
setwd("C:/Users/R/OneDrive/coursera/reproducibleResearch/week1Assignment")

#if(!exists("activity")){
   # unzip("activity.zip")
  activity<- read.csv("activity.csv")
#}

activity$date<-ymd(as.character(activity$date))
```


## What is mean total number of steps taken per day?  
(ignored for median and mean values of 0)
```{r cache=TRUE}
activityByDay<- group_by(activity[,c(1:2)],date) %>%summarise(median(steps[steps>0]),
                                                              mean(steps[steps>0]),
                                                              sum(steps))

names(activityByDay)<-c("date","steps-Mean","steps-Median","steps")

totalStepsaDay <- ggplot(activityByDay, aes(x=date, weights=steps)) + 
  geom_bar()+labs(y="total of steps a day")
print(totalStepsaDay)

activityByDay.melt<- melt(activityByDay[,c(1:3)], id.vars="date",variable.name ="Aggregate", value.name="steps")

MeanAndMediumADay <-ggplot(data=activityByDay.melt,aes(date,steps,col=Aggregate)) + geom_point(alpha=0.3) + scale_color_manual(values = c("steps-Mean" = 'red','steps-Median' = 'blue')) 
   
print(MeanAndMediumADay)

```   


## What is the average daily activity pattern?
```{r cache=TRUE}
activityByInterval<- group_by(activity[,-2],interval) %>%summarise(mean(steps[steps>0],na.rm=TRUE))
names(activityByInterval)<- c("interval", "stepMean")
 
IntervalMean <- ggplot(data=activityByInterval,aes(x=interval,y=stepMean)) + geom_point(alpha=.3)
print(IntervalMean)

maxInterval <- filter(activityByInterval,stepMean==max(activityByInterval$stepMean, na.rm = TRUE))
maxInterval
```


## Imputing missing values
```{r cache=TRUE}
NumberOfNA <- sum(is.na(activity$steps))
NumberOfNA

activity$steps<-na.locf(activity$steps,na.rm = F,fromLast = F, rule=2)
activity$steps<-na.locf(activity$steps,na.rm = F,fromLast = T,rule=2)
NumberOfNA_afterReplacement <- sum(is.na(activity$steps))
NumberOfNA_afterReplacement


activityByDayNoNA<- group_by(activity[,c(1:2)],date) %>%summarise(median(steps[steps>0]),
                                                              mean(steps[steps>0]),
                                                              sum(steps))

names(activityByDayNoNA)<-c("date","steps-Mean2","steps-Median2","steps2")

totalStepsaDay <- ggplot(activityByDayNoNA, aes(x=date, weights=steps2)) + 
  geom_bar()+labs(y="total of steps a day")
print(totalStepsaDay)

activityByDayNoNA.melt<- melt(activityByDayNoNA[,c(1:3)], id.vars="date",variable.name ="Aggregate", value.name="steps2")

MeanAndMediumADay <-ggplot(data=activityByDayNoNA.melt,aes(date,steps2,col=Aggregate)) + geom_point(alpha=0.3) + scale_color_manual(values = c("steps-Mean2" = 'red','steps-Median2' = 'blue')) 
   
print(MeanAndMediumADay)

averages_With_Na_replaced<-summarise_each(activityByDayNoNA[complete.cases(activityByDayNoNA),][,c(-1)],funs(mean))
averages_With_Na_not_replaced<-summarise_each(activityByDay[complete.cases(activityByDay),][,c(-1)],funs(mean))

averages_With_Na_not_replaced
averages_With_Na_replaced
```


## Are there differences in activity patterns between weekdays and weekends?
